### PR TITLE
Backend for DAO

### PR DESCRIPTION
**Pull request by tupui**
First version for the DAO on the chain side.

### CODE REVIEW

**Comment by tupui** [comment]
@0xExp-po when you are ready to test the new bindings, you can try this branch. You have functions to `register`, `vote`, `get_proposal` and `get_dao`. I did not yet deploy that version of the contract, let me know if you want me to update the current contract with it.

**Comment by 0xExp-po** [comment]
based on your mockup, I need to show the voters separately - maintainers, contributors and community.
but in the contract, I can't find such info from the proposal data.
where can I find that info?

**Comment by tupui** [comment]
For now just have 2 sections. Maintainers and community. You should already have the maintainers list as this is in the project info.

**Comment by tupui** [comment]
@0xExp-po do you have other comments? If not I can get deploy this and you can start to use it on the frontend side.

**Comment by 0xExp-po** [comment]
I think I can do everything in frontend with this right now

**Pull request merged**
